"""PRSubmitter — submits validated patches as GitHub pull requests."""

from __future__ import annotations

from typing import TYPE_CHECKING

from summer_puppy.dev_bot.models import (
    DevBotPR,
    PatchCandidate,
    PatchStatus,
    PatchTestResult,
    PROutcome,
    UserStory,
)

if TYPE_CHECKING:
    from summer_puppy.dev_bot.github_client import GitHubClient

_PATCH_TYPE_TO_PATH: dict[str, str] = {
    "firewall_rule": "security/firewall",
    "iam_policy": "security/iam",
    "edr_config": "security/edr",
    "remediation_script": "security/scripts",
    "configuration_change": "security/config",
    "network_policy": "security/network",
}

_PATCH_TYPE_TO_EXT: dict[str, str] = {
    "firewall_rule": "conf",
    "iam_policy": "json",
    "edr_config": "yaml",
    "remediation_script": "sh",
    "configuration_change": "yaml",
    "network_policy": "yaml",
}


def _file_path_for_patch(patch: PatchCandidate) -> str:
    if patch.target_files:
        return patch.target_files[0]
    folder = _PATCH_TYPE_TO_PATH.get(patch.patch_type, "security/patches")
    ext = _PATCH_TYPE_TO_EXT.get(patch.patch_type, "txt")
    return f"{folder}/{patch.patch_id[:8]}.{ext}"


def _build_pr_body(
    patch: PatchCandidate, test_result: PatchTestResult, story: UserStory
) -> str:
    criteria_lines = "\n".join(f"- {c}" for c in story.acceptance_criteria)
    check_lines = "\n".join(
        f"- {'PASS' if c.passed else 'FAIL'} `{c.check_name}`: {c.detail}"
        for c in test_result.checks
    )
    rollback = patch.rollback_content or "(no rollback provided)"

    return (
        f"## Security Patch\n\n"
        f"**Story:** {story.title}\n\n"
        f"**Description:**\n{story.description}\n\n"
        f"## Acceptance Criteria\n\n{criteria_lines}\n\n"
        f"## Pre-Submit Test Results\n\n"
        f"**Overall:** {'PASSED' if test_result.passed else 'FAILED'}\n\n"
        f"{check_lines}\n\n"
        f"**Summary:** {test_result.summary}\n\n"
        f"## Rollback Instructions\n\n```\n{rollback}\n```\n\n"
        f"---\n*Generated by SummerPuppy DevBot — patch_id: {patch.patch_id}*"
    )


class PRSubmitter:
    """Submits validated patch candidates as GitHub pull requests."""

    def __init__(
        self,
        github_client: GitHubClient,
        default_repo: str,
        default_base_branch: str = "main",
    ) -> None:
        self._github_client = github_client
        self._default_repo = default_repo
        self._default_base_branch = default_base_branch

    async def submit(
        self,
        patch: PatchCandidate,
        test_result: PatchTestResult,
        story: UserStory,
    ) -> DevBotPR:
        """Submit a patch as a PR. Returns DevBotPR with ABANDONED status if test failed."""
        if not test_result.passed:
            return DevBotPR(
                patch_id=patch.patch_id,
                story_id=story.story_id,
                customer_id=patch.customer_id,
                correlation_id=patch.correlation_id,
                github_repo=self._default_repo,
                status=PatchStatus.ABANDONED,
                outcome=PROutcome.REJECTED,
                pr_title=f"[SummerPuppy] {patch.title}",
                pr_body="",
                review_notes=f"Pre-submit test failed: {test_result.summary}",
            )

        branch_name = f"sumpy/patch/{patch.patch_id[:8]}"
        pr_title = f"[SummerPuppy] {patch.title}"
        pr_body = _build_pr_body(patch, test_result, story)
        file_path = _file_path_for_patch(patch)

        await self._github_client.create_branch(
            repo=self._default_repo,
            branch=branch_name,
            base_branch=self._default_base_branch,
        )
        await self._github_client.create_file(
            repo=self._default_repo,
            branch=branch_name,
            path=file_path,
            content=patch.content,
            message=f"[SummerPuppy] Add patch {patch.patch_id[:8]}",
        )
        pr_number, pr_url = await self._github_client.create_pull_request(
            repo=self._default_repo,
            branch=branch_name,
            title=pr_title,
            body=pr_body,
            base_branch=self._default_base_branch,
        )

        return DevBotPR(
            patch_id=patch.patch_id,
            story_id=story.story_id,
            customer_id=patch.customer_id,
            correlation_id=patch.correlation_id,
            github_pr_number=pr_number,
            github_pr_url=pr_url,
            github_repo=self._default_repo,
            branch_name=branch_name,
            pr_title=pr_title,
            pr_body=pr_body,
            status=PatchStatus.PR_OPEN,
            outcome=PROutcome.PENDING,
        )
