"""Tests for Trainer — strict TDD, tests written before implementation."""

from __future__ import annotations

from typing import Any

import pytest

from summer_puppy.audit.logger import InMemoryAuditLogger
from summer_puppy.skills.evaluator import RunEvaluator
from summer_puppy.skills.kb import InMemorySkillKnowledgeBase
from summer_puppy.skills.models import PromotionLevel, TrainingRecommendation
from summer_puppy.skills.promotion import PromotionEngine
from summer_puppy.skills.registry import InMemorySkillRegistry
from summer_puppy.skills.trainer import Trainer

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_context(
    *,
    agent_id: str = "agent-1",
    customer_id: str = "cust-1",
    correlation_id: str = "corr-1",
    outcome_success: bool = True,
    qa_status: str = "PASSED",
    execution_status: str = "COMPLETED",
    confidence_score: float = 0.9,
    approval_method: str = "AUTO_APPROVED",
) -> dict[str, Any]:
    return {
        "agent_id": agent_id,
        "customer_id": customer_id,
        "correlation_id": correlation_id,
        "outcome_success": outcome_success,
        "qa_status": qa_status,
        "execution_status": execution_status,
        "confidence_score": confidence_score,
        "approval_method": approval_method,
    }


def _make_artifact(
    artifact_id: str = "art-1",
    artifact_type: str = "CODE_PATCH",
    source_run_id: str = "run-1",
    content: str = "patch content",
    action_class: str = "patch_deployment",
) -> dict[str, Any]:
    return {
        "artifact_id": artifact_id,
        "artifact_type": artifact_type,
        "source_run_id": source_run_id,
        "content": content,
        "action_class": action_class,
    }


def _build_trainer() -> tuple[
    Trainer, InMemorySkillRegistry, InMemorySkillKnowledgeBase, InMemoryAuditLogger
]:
    evaluator = RunEvaluator()
    promotion_engine = PromotionEngine()
    registry = InMemorySkillRegistry()
    kb = InMemorySkillKnowledgeBase()
    audit = InMemoryAuditLogger()
    trainer = Trainer(
        evaluator=evaluator,
        promotion_engine=promotion_engine,
        skill_registry=registry,
        knowledge_base=kb,
        audit_logger=audit,
    )
    return trainer, registry, kb, audit


# ---------------------------------------------------------------------------
# Trainer tests
# ---------------------------------------------------------------------------


class TestTrainer:
    """Tests for Trainer.review_and_train()."""

    async def test_returns_training_recommendation(self) -> None:
        trainer, *_ = _build_trainer()
        ctx = _make_context()
        result = await trainer.review_and_train(ctx, [_make_artifact()])
        assert isinstance(result, TrainingRecommendation)

    async def test_calls_evaluator_with_context_summary(self) -> None:
        """The review_id in the result should match the review produced by the evaluator."""
        trainer, *_ = _build_trainer()
        ctx = _make_context(correlation_id="corr-99")
        result = await trainer.review_and_train(ctx, [_make_artifact()])
        # review_id should be a non-empty string generated by the evaluator
        assert result.review_id

    async def test_calls_promotion_engine_classify_artifacts(self) -> None:
        """kb_promotions should reflect the promotion engine's decisions."""
        trainer, *_ = _build_trainer()
        ctx = _make_context(outcome_success=True, qa_status="PASSED")
        artifacts = [_make_artifact(artifact_type="CODE_PATCH", artifact_id="art-promo")]
        result = await trainer.review_and_train(ctx, artifacts)
        # CODE_PATCH with success + high QA -> TEAM_KB -> should appear in kb_promotions
        assert "art-promo" in result.kb_promotions

    async def test_updates_skill_profile_total_runs_incremented(self) -> None:
        trainer, registry, *_ = _build_trainer()
        ctx = _make_context(agent_id="agent-x")
        await trainer.review_and_train(ctx, [_make_artifact()])
        profile = registry.get_agent_profile("agent-x")
        assert profile is not None
        assert profile.total_runs == 1

    async def test_successful_outcome_increments_successful_runs(self) -> None:
        trainer, registry, *_ = _build_trainer()
        ctx = _make_context(agent_id="agent-s", outcome_success=True)
        await trainer.review_and_train(ctx, [_make_artifact()])
        profile = registry.get_agent_profile("agent-s")
        assert profile is not None
        assert profile.successful_runs == 1
        assert profile.failed_runs == 0

    async def test_failed_outcome_increments_failed_runs(self) -> None:
        trainer, registry, *_ = _build_trainer()
        ctx = _make_context(agent_id="agent-f", outcome_success=False)
        await trainer.review_and_train(ctx, [_make_artifact()])
        profile = registry.get_agent_profile("agent-f")
        assert profile is not None
        assert profile.failed_runs == 1
        assert profile.successful_runs == 0

    async def test_human_override_increments_human_override_count(self) -> None:
        trainer, registry, *_ = _build_trainer()
        ctx = _make_context(agent_id="agent-h", approval_method="HUMAN_APPROVED")
        await trainer.review_and_train(ctx, [_make_artifact()])
        profile = registry.get_agent_profile("agent-h")
        assert profile is not None
        assert profile.human_override_count == 1

    async def test_creates_skill_profile_if_none_exists(self) -> None:
        trainer, registry, *_ = _build_trainer()
        # Verify no profile exists initially
        assert registry.get_agent_profile("new-agent") is None
        ctx = _make_context(agent_id="new-agent", customer_id="cust-new")
        await trainer.review_and_train(ctx, [])
        profile = registry.get_agent_profile("new-agent")
        assert profile is not None
        assert profile.agent_id == "new-agent"
        assert profile.customer_id == "cust-new"

    async def test_promotes_team_kb_artifacts_to_knowledge_base(self) -> None:
        trainer, _, kb, _ = _build_trainer()
        ctx = _make_context(outcome_success=True, qa_status="PASSED", customer_id="cust-kb")
        artifacts = [
            _make_artifact(
                artifact_id="art-team",
                artifact_type="CODE_PATCH",
                content="team patch",
            )
        ]
        await trainer.review_and_train(ctx, artifacts)
        articles = kb.list_articles("cust-kb", promotion_level=PromotionLevel.TEAM_KB)
        assert len(articles) == 1
        assert articles[0].title == "KB from art-team"
        assert articles[0].content == "team patch"

    async def test_promotes_global_kb_artifacts_to_knowledge_base(self) -> None:
        """GLOBAL_KB promotions should also create a KnowledgeArticle.

        Note: the current PromotionEngine never produces GLOBAL_KB. We still
        test the Trainer path by pre-seeding the classification outcome indirectly.
        Since real PromotionEngine doesn't return GLOBAL_KB for any artifact type,
        we verify the Trainer handles it if it were to occur by testing end-to-end
        with an artifact type that does get promoted (TEAM_KB) and checking the
        resulting article.  The GLOBAL_KB branch will be tested once the engine
        supports it. For now we confirm articles are stored for TEAM_KB (the
        adjacent branch).
        """
        trainer, _, kb, _ = _build_trainer()
        ctx = _make_context(outcome_success=True, qa_status="PASSED", customer_id="cust-g")
        artifacts = [
            _make_artifact(
                artifact_id="art-global",
                artifact_type="DETECTION_RULE",
                content="global rule",
            )
        ]
        await trainer.review_and_train(ctx, artifacts)
        articles = kb.list_articles("cust-g", promotion_level=PromotionLevel.TEAM_KB)
        assert len(articles) == 1
        assert articles[0].content == "global rule"
        assert articles[0].source_run_id == "corr-1"

    async def test_promotes_playbook_template_to_knowledge_base(self) -> None:
        trainer, _, kb, _ = _build_trainer()
        ctx = _make_context(
            outcome_success=True,
            qa_status="PASSED",
            customer_id="cust-pb",
        )
        artifacts = [
            _make_artifact(
                artifact_id="art-pb",
                artifact_type="RUNBOOK",
                content="runbook steps",
                action_class="patch_deployment",
            )
        ]
        await trainer.review_and_train(ctx, artifacts)
        playbooks = kb.list_playbooks("cust-pb")
        assert len(playbooks) == 1
        assert playbooks[0].name == "Playbook from art-pb"
        assert playbooks[0].steps == ["runbook steps"]

    async def test_skips_discard_no_kb_article(self) -> None:
        trainer, _, kb, _ = _build_trainer()
        ctx = _make_context(
            outcome_success=False,
            confidence_score=0.1,
            customer_id="cust-disc",
        )
        artifacts = [_make_artifact(artifact_id="art-disc", artifact_type="CODE_PATCH")]
        await trainer.review_and_train(ctx, artifacts)
        articles = kb.list_articles("cust-disc")
        playbooks = kb.list_playbooks("cust-disc")
        assert len(articles) == 0
        assert len(playbooks) == 0

    async def test_skips_run_record_no_kb_article(self) -> None:
        trainer, _, kb, _ = _build_trainer()
        # outcome_success=True but qa_reliability < 0.8 -> RUN_RECORD
        ctx = _make_context(
            outcome_success=True,
            qa_status="PENDING",  # qa_reliability = 0.5
            customer_id="cust-rr",
        )
        artifacts = [_make_artifact(artifact_id="art-rr", artifact_type="CODE_PATCH")]
        await trainer.review_and_train(ctx, artifacts)
        articles = kb.list_articles("cust-rr")
        playbooks = kb.list_playbooks("cust-rr")
        assert len(articles) == 0
        assert len(playbooks) == 0

    async def test_kb_promotions_list_contains_promoted_artifact_ids(self) -> None:
        trainer, *_ = _build_trainer()
        ctx = _make_context(outcome_success=True, qa_status="PASSED")
        artifacts = [
            _make_artifact(artifact_id="art-a", artifact_type="CODE_PATCH"),
            _make_artifact(artifact_id="art-b", artifact_type="RUNBOOK"),
        ]
        result = await trainer.review_and_train(ctx, artifacts)
        # CODE_PATCH -> TEAM_KB, RUNBOOK -> PLAYBOOK_TEMPLATE
        assert "art-a" in result.kb_promotions
        assert "art-b" in result.kb_promotions

    async def test_multiple_artifacts_each_correct_treatment(self) -> None:
        trainer, _, kb, _ = _build_trainer()
        ctx = _make_context(
            outcome_success=True,
            qa_status="PASSED",
            customer_id="cust-multi",
        )
        artifacts = [
            _make_artifact(artifact_id="art-1", artifact_type="CODE_PATCH", content="patch1"),
            _make_artifact(artifact_id="art-2", artifact_type="RUNBOOK", content="runbook1"),
            _make_artifact(artifact_id="art-3", artifact_type="THREAT_REPORT", content="report1"),
        ]
        result = await trainer.review_and_train(ctx, artifacts)
        # CODE_PATCH -> TEAM_KB article, RUNBOOK -> PLAYBOOK, THREAT_REPORT -> RUN_RECORD (skip)
        articles = kb.list_articles("cust-multi", promotion_level=PromotionLevel.TEAM_KB)
        assert len(articles) == 1
        assert articles[0].content == "patch1"

        playbooks = kb.list_playbooks("cust-multi")
        assert len(playbooks) == 1
        assert playbooks[0].steps == ["runbook1"]

        # art-1 (TEAM_KB) and art-2 (PLAYBOOK_TEMPLATE) should be in kb_promotions
        assert "art-1" in result.kb_promotions
        assert "art-2" in result.kb_promotions
        # art-3 (RUN_RECORD) should NOT be in kb_promotions
        assert "art-3" not in result.kb_promotions

    async def test_empty_artifacts_no_error_empty_promotions(self) -> None:
        trainer, *_ = _build_trainer()
        ctx = _make_context()
        result = await trainer.review_and_train(ctx, [])
        assert result.kb_promotions == []

    async def test_qa_pass_rate_calculated_correctly(self) -> None:
        trainer, registry, *_ = _build_trainer()
        ctx_success = _make_context(agent_id="agent-qr", outcome_success=True)
        ctx_fail = _make_context(agent_id="agent-qr", outcome_success=False)
        await trainer.review_and_train(ctx_success, [])
        await trainer.review_and_train(ctx_fail, [])
        await trainer.review_and_train(ctx_success, [])

        profile = registry.get_agent_profile("agent-qr")
        assert profile is not None
        assert profile.total_runs == 3
        assert profile.successful_runs == 2
        assert profile.failed_runs == 1
        assert profile.qa_pass_rate == pytest.approx(2 / 3)

    async def test_skill_updates_in_result(self) -> None:
        trainer, *_ = _build_trainer()
        ctx = _make_context(agent_id="agent-su")
        result = await trainer.review_and_train(ctx, [])
        assert result.skill_updates["agent_id"] == "agent-su"
        assert result.skill_updates["total_runs"] == 1

    async def test_trust_adjustments_empty(self) -> None:
        trainer, *_ = _build_trainer()
        ctx = _make_context()
        result = await trainer.review_and_train(ctx, [])
        assert result.trust_adjustments == {}

    async def test_default_agent_id_when_missing(self) -> None:
        trainer, registry, *_ = _build_trainer()
        ctx = _make_context()
        del ctx["agent_id"]
        await trainer.review_and_train(ctx, [])
        profile = registry.get_agent_profile("default")
        assert profile is not None
        assert profile.total_runs == 1

    async def test_profile_last_updated_utc_changes(self) -> None:
        trainer, registry, *_ = _build_trainer()
        ctx = _make_context(agent_id="agent-ts")
        await trainer.review_and_train(ctx, [])
        profile = registry.get_agent_profile("agent-ts")
        assert profile is not None
        assert profile.last_updated_utc is not None

    async def test_playbook_action_class_from_artifact(self) -> None:
        trainer, _, kb, _ = _build_trainer()
        ctx = _make_context(
            outcome_success=True,
            qa_status="PASSED",
            customer_id="cust-ac",
        )
        artifacts = [
            _make_artifact(
                artifact_id="art-ac",
                artifact_type="RUNBOOK",
                action_class="network_isolation",
            )
        ]
        await trainer.review_and_train(ctx, artifacts)
        playbooks = kb.list_playbooks("cust-ac")
        assert len(playbooks) == 1
        assert playbooks[0].action_class == "network_isolation"
